$('.owl-carousel').owlCarousel({
    rtl:true,
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:4
        },
        600:{
            items:7
        },
        1000:{
            items:9
        }
    }
})